#!/bin/sh
# This is the Daimonin loop & log script.

builddir="$HOME/build"
logsdir="/var/www/html/logs"
CMDNAME="valgrind ./daimonin_server"
maxrestart=500

for (( logcount = 1; logcount < $maxrestart; logcount++ )); do
    echo "### Start the server." 1>&2
    rm -fr $builddir/server/data/tmp/*
    cd $builddir/server
    $CMDNAME -d -log ,c$logcount 2>$builddir/server/data/log/t$logcount

    retexe=$?
    echo ">>> We have $retexe as shutdown" 1>&2
    echo ">>> We have $retexe as shutdown" 1>>$builddir/server/data/log/t$logcount 2>&1

    # 127 comes from a badly critical error like a non existing daimonin_server binary and such
    if [ $retexe -eq 127 ]; then
        echo ">>> Critical error!" 1>>$builddir/server/data/log/t$logcount 2>&1
    # restart
    elif [ $retexe -eq 253 ]; then
        echo ">>> Restart!" 1>>$builddir/server/data/log/t$logcount 2>&1
    # unknown
    elif [ $retexe -eq 254 ]; then
        echo ">>> Unknown reason for shutdown!" 1>>$builddir/server/data/log/t$logcount 2>&1
    # server crashed in the startup
    elif [ $retexe -eq 255 ]; then
        echo ">>> Crash at startup!" 1>>$builddir/server/data/log/t$logcount 2>&1
    fi

    gzip $builddir/server/data/log/c$logcount
    mv $builddir/server/data/log/c$logcount.gz $logsdir/`/bin/date +%y%m%d_%H-%M-%S_%Z`-$retexe-chat.gz
    gzip $builddir/server/data/log/t$logcount
    mv $builddir/server/data/log/t$logcount.gz $logsdir/`/bin/date +%y%m%d_%H-%M-%S_%Z`-$retexe-tech.gz

    if [ -f core ]; then
        mv $builddir/server/core $builddir/server/core.$logcount
        gzip $builddir/server/core.$logcount
        mv $builddir/server/core.$logcount.gz $logsdir/`/bin/date +%y%m%d_%H-%M-%S_%Z`-crash.gz
    fi

    $builddir/project_tools/bash-scripts/build.sh
done

exit 0
