#!/bin/sh
# This is the Daimonin loop & log script.

builddir="$HOME/build"
logsdir="/var/www/html/logs"
CMDNAME="valgrind ./daimonin_server"
maxrestart=500

for (( logcount = 1; logcount < $maxrestart; logcount++ )); do
    fromtime=`/bin/date +%y%m%d_%H-%M-%S_%Z`
    echo "$fromtime" >$HOME/fromtime
    logfile="$logsdir/$fromtime"
    tlogfile="$logfile-tech.txt"
    clogfile="$logfile-chat.txt"

    echo "### Start the server." 1>&2
    cd $builddir/server
    $CMDNAME -d -log ,$clogfile 2>$tlogfile

    retexe=$?
    echo ">>> We have $retexe as shutdown" 1>&2
    echo ">>> We have $retexe as shutdown" 1>>$tlogfile 2>&1

#    # 127 comes from a badly critical error like a non existing daimonin_server binary and such
#    if [ $retexe -eq 127 ]; then
#        echo ">>> Critical error!" 1>>$logfile$tlog 2>&1
#    # restart
#    elif [ $retexe -eq 253 ]; then
#        echo ">>> Restart!" 1>>$logfile$tlog 2>&1
#    # unknown
#    elif [ $retexe -eq 254 ]; then
#        echo ">>> Unknown reason for shutdown!" 1>>$logfile$tlog 2>&1
#    # server crashed in the startup
#    elif [ $retexe -eq 255 ]; then
#        echo ">>> Crash at startup!" 1>>$logfile$tlog 2>&1
#    fi

    totime=`/bin/date +%y%m%d_%H-%M-%S_%Z`
    tar -czf $logfile-$totime-$retexe.tar.gz $tlogfile $clogfile
    rm $tlogfile $clogfile
    echo "" >$HOME/fromtime

    if [ -f core ]; then
        mv $builddir/server/core $builddir/server/core.$logcount
        gzip $builddir/server/core.$logcount
        mv $builddir/server/core.$logcount.gz $logsdir/`/bin/date +%y%m%d_%H-%M-%S_%Z`-crash.gz
    fi

    $builddir/project_tools/bash-scripts/build.sh
done

exit 0
