#!/bin/sh
# This is the Daimonin loop & log script.

serverdir="$HOME/build/server"
logsdir="/var/www/html/logs"
CMDNAME="valgrind ./daimonin_server"
maxrestart=500

for (( logcount = 1; logcount < $maxrestart; logcount++ )); do
    echo "### Start the server." 1>&2
    rm -fr $serverdir/data/tmp/*
    cd $serverdir
    $CMDNAME -d -log $serverdir/data/log/t$logcount,$serverdir/data/log/c$logcount

    retexe=$?
    echo ">>> We have $retexe as shutdown" 1>&2
    echo ">>> We have $retexe as shutdown" 1>>$serverdir/data/log/t$logcount 2>&1

    # 127 comes from a badly critical error like a non existing daimonin_server binary and such
    if [ $retexe -eq 127 ]; then
        echo ">>> Critical error!" 1>>$serverdir/data/log/t$logcount 2>&1
    # restart
    elif [ $retexe -eq 253 ]; then
        echo ">>> Restart!" 1>>$serverdir/data/log/t$logcount 2>&1
    # unknown
    elif [ $retexe -eq 254 ]; then
        echo ">>> Unknown reason for shutdown!" 1>>$serverdir/data/log/t$logcount 2>&1
    # server crashed in the startup
    elif [ $retexe -eq 255 ]; then
        echo ">>> Crash at startup!" 1>>$serverdir/data/log/t$logcount 2>&1
    fi

    gzip $serverdir/data/log/c$logcount
    mv $serverdir/data/log/c$logcount.gz $logsdir/`/bin/date +%y%m%d_%H-%M-%S_%Z`-$retexe-chat.gz
    gzip $serverdir/data/log/t$logcount
    mv $serverdir/data/log/t$logcount.gz $logsdir/`/bin/date +%y%m%d_%H-%M-%S_%Z`-$retexe-tech.gz

    if [ -f core ]; then
        mv $serverdir/core $serverdir/core.$logcount
        gzip $serverdir/core.$logcount
        mv $serverdir/core.$logcount.gz $logsdir/`/bin/date +%y%m%d_%H-%M-%S_%Z`-crash.gz
    fi

    $HOME/build.sh
done

exit 0
